import type { Metadata } from "next";

import BackgroundProvider from "@/components/Providers/background.provider";
import ProgressBarProvider from "@/components/Providers/progressbar.provider";
import { GetMe } from "@/requests/auth";

import LayoutContent from "./layout.content";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const me = (await GetMe()).data;
  if (!me) return <p>No User!</p>;
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ProgressBarProvider>
          <BackgroundProvider>
            <LayoutContent userData={me}>{children}</LayoutContent>
          </BackgroundProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
