import type { Metadata } from "next";

import BackgroundProvider from "@/components/Providers/background.provider";
import ProgressBarProvider from "@/components/Providers/progressbar.provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ProgressBarProvider>
          <BackgroundProvider>{children}</BackgroundProvider>
        </ProgressBarProvider>
      </body>
    </html>
  );
}
